baseurl = "https://lopez-504.github.io/"
languageCode = "en-us"
title = "Jorge LÃ³pez Blog"

# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.

theme = "hugo-theme-terminal"
pagination.pagerSize = 5

[params]
math = true		# Latex